baseurl = "https://prasadghole.github.io"
title = "Musing on daily development activities"
copyright = "Copyright (c) 2008 - 2018, Prasad Ghole"
canonifyurls = true
paginate = 3
theme = "hugo-paper"

[params]
    author = "John Doe"
    locale = "en-US"
    rootlink = "/"
