baseurl = "https://prasadghole.github.io"
title = "Musing on daily development activities"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3
theme = "charaka-hugo-theme"

[params]
    author = "John Doe"
    locale = "en-US"
    rootlink = "/"
